name: CI

on: [ push, pull_request ]

jobs:
  lint-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: TrueBrain/actions-flake8@v1.4.1
  lint-local:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - run: pip install tox
      - run: tox -e mypy
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            py: 3.9.1
          - os: macos-latest
            py: 3.9.1
          - os: ubuntu-latest
            py: 3.9.1
          - os: ubuntu-latest
            py: 3.8.7
          - os: ubuntu-latest
            py: 3.7.9
    runs-on: ${{ matrix.os }}
    steps:
      - run: printenv
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - run: pip install tox
      - run: tox -e py -- -vvv
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: ${{ matrix.os }}

  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment: deploy
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      TWINE_REPOSITORY: ${{ secrets.TWINE_REPOSITORY }}
    runs-on: ubuntu-latest
    needs: [mypy, test]
    steps:
      - run: printenv
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - run: pip install -r requirements-dev.txt
      - run: python setup.py bdist_wheel
      - run: twine check dist/*
      - run: twine upload dist/*
